version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    versioning-strategy: 'lockfile-only'
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    commit-message:
      prefix: 'chore'
