version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: 'widen'
    range-mapping:
      'caret': 'widen'
      'tilde': 'widen'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
